# SBANN
## Standard boring ass neural network

Import necessary packages

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

2023-05-11 11:04:23.873414: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Data

Define core features of the dataset

In [19]:
dim = 3
numpart = 30
latent_dim = 4

Import and reshape data

In [2]:
fname="/Users/lorenzobarbiero/Downloads/test_30_5_0.1_0.3_100000_0.08_x.txt"
with open(fname) as f:
    data = [
        [float(i.strip()) for i in s.split(" ") if i != ""]
        for s in f.read().split("\n")
        if s != ""]

In [3]:
print(data[1])

[2.463258, 3.476661, 0.895062, 2.826777, 1.318252, 0.580524, 3.907947, 3.56574, 0.736961, 2.618962, 2.522231, 2.524339, 1.076911, 0.545973, 2.038803, 4.332246, 3.943481, 2.134315, 1.78288, 4.109908, 4.346558, 1.512695, 2.515875, 3.685902, 2.443689, 1.608195, 4.234131, 2.369365, 0.482387, 4.264563, 0.060537, 2.18895, 4.37735, 3.75555, 0.352204, 3.381785, 1.83043, 2.947288, 4.922763, 3.012182, 4.209706, 0.292631, 1.006227, 1.628173, 4.330286, 2.071739, 3.347057, 2.429691, 2.564176, 1.569708, 2.911609, 1.734956, 1.916557, 1.803327, 0.595494, 3.611851, 1.320901, 1.732421, 4.257394, 0.572481, 1.624797, 1.648793, 0.526701, 0.778746, 2.243945, 1.063158, 4.196413, 0.670515, 0.562519, 1.520246, -0.065401, 1.31771, 3.552185, 1.616999, 2.326026, 0.677477, 2.07685, 2.766973, 2.195747, 0.609719, 0.259181, 0.559955, 1.700786, 1.536886, 3.848572, 1.513618, 3.545498, 2.927643, 4.323117, 2.396616]


In [20]:
vcs = np.array(data).reshape((-1,numpart,dim))
print(vcs.shape)

(100000, 30, 3)


Sort points

In [5]:
idx = np.lexsort((vcs[:,:,1], vcs[:,:,0]))

# Use the indices to sort each step while maintaining the rows intact
sorted_vcs = np.empty_like(vcs)
for i in range(len(vcs)):
    sorted_vcs[i] = vcs[i][idx[i]]
    
print(sorted_vcs.shape,"\n",sorted_vcs[1])

(100000, 30, 3) 
 [[ 0.060537  2.18895   4.37735 ]
 [ 0.559955  1.700786  1.536886]
 [ 0.595494  3.611851  1.320901]
 [ 0.677477  2.07685   2.766973]
 [ 0.778746  2.243945  1.063158]
 [ 1.006227  1.628173  4.330286]
 [ 1.076911  0.545973  2.038803]
 [ 1.512695  2.515875  3.685902]
 [ 1.520246 -0.065401  1.31771 ]
 [ 1.624797  1.648793  0.526701]
 [ 1.732421  4.257394  0.572481]
 [ 1.734956  1.916557  1.803327]
 [ 1.78288   4.109908  4.346558]
 [ 1.83043   2.947288  4.922763]
 [ 2.071739  3.347057  2.429691]
 [ 2.195747  0.609719  0.259181]
 [ 2.369365  0.482387  4.264563]
 [ 2.443689  1.608195  4.234131]
 [ 2.463258  3.476661  0.895062]
 [ 2.564176  1.569708  2.911609]
 [ 2.618962  2.522231  2.524339]
 [ 2.826777  1.318252  0.580524]
 [ 2.927643  4.323117  2.396616]
 [ 3.012182  4.209706  0.292631]
 [ 3.552185  1.616999  2.326026]
 [ 3.75555   0.352204  3.381785]
 [ 3.848572  1.513618  3.545498]
 [ 3.907947  3.56574   0.736961]
 [ 4.196413  0.670515  0.562519]
 [ 4.332246  3.943481  2.

In [21]:
sorted_vcs = sorted_vcs.reshape((-1,90))
print(sorted_vcs.shape,"\n",sorted_vcs[1])

(100000, 90) 
 [ 0.060537  2.18895   4.37735   0.559955  1.700786  1.536886  0.595494
  3.611851  1.320901  0.677477  2.07685   2.766973  0.778746  2.243945
  1.063158  1.006227  1.628173  4.330286  1.076911  0.545973  2.038803
  1.512695  2.515875  3.685902  1.520246 -0.065401  1.31771   1.624797
  1.648793  0.526701  1.732421  4.257394  0.572481  1.734956  1.916557
  1.803327  1.78288   4.109908  4.346558  1.83043   2.947288  4.922763
  2.071739  3.347057  2.429691  2.195747  0.609719  0.259181  2.369365
  0.482387  4.264563  2.443689  1.608195  4.234131  2.463258  3.476661
  0.895062  2.564176  1.569708  2.911609  2.618962  2.522231  2.524339
  2.826777  1.318252  0.580524  2.927643  4.323117  2.396616  3.012182
  4.209706  0.292631  3.552185  1.616999  2.326026  3.75555   0.352204
  3.381785  3.848572  1.513618  3.545498  3.907947  3.56574   0.736961
  4.196413  0.670515  0.562519  4.332246  3.943481  2.134315]


Split in training and test set

In [7]:
train_perc=0.8
trainset = sorted_vcs[:int(train_perc*len(data))]
print(trainset.shape)
testset = sorted_vcs[int(train_perc*len(data)):]

(80000, 90)


### Sampling class

In [8]:
class Sampling(layers.Layer):
    """Uses (z_mean, z_log_var) to sample z, the vector encoding a digit."""

    def call(self, inputs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

### Encoder

In [16]:
input_shape = (numpart*dim)
inputs = layers.Input(shape=input_shape)
x = layers.Dens(int(numpart*dim*2/3), activation='relu')(inputs)
x = layers.Dense(int(numpart*dim*1/2), activation='relu')(x)
x = layers.Dense(int(numpart*dim*1/4), activation='relu')(x)
z_mean = layers.Dense(latent_dim, name='z_mean')(x)
z_log_var = layers.Dense(latent_dim, name='z_log_var')(x)
z = Sampling()([z_mean, z_log_var])
encoder = keras.Model(inputs, [z_mean, z_log_var, z], name="encoder")
encoder.summary()

Model: "encoder"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_6 (InputLayer)           [(None, 90)]         0           []                               
                                                                                                  
 dense_17 (Dense)               (None, 60)           5460        ['input_6[0][0]']                
                                                                                                  
 dense_18 (Dense)               (None, 30)           1830        ['dense_17[0][0]']               
                                                                                                  
 dense_19 (Dense)               (None, 15)           465         ['dense_18[0][0]']               
                                                                                            

### Decoder

In [13]:
latent_inputs = keras.Input(shape=(latent_dim,))
x = layers.Dense(int(numpart*dim*1/4)m, activation="relu")(latent_inputs)
x = layers.Dense(int(numpart*dim*1/2), activation="relu")(x)
x = layers.Dense(int(numpart*dim*2/3), activation="relu")(x)
decoder_outputs = layers.Dense(numpart*dim, activation="relu")(x)
decoder = keras.Model(latent_inputs, decoder_outputs, name="decoder")
decoder.summary()

Model: "decoder"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_13 (Dense)            (None, 15)                75        
                                                                 
 dense_14 (Dense)            (None, 30)                480       
                                                                 
 dense_15 (Dense)            (None, 60)                1860      
                                                                 
 dense_16 (Dense)            (None, 90)                5490      
                                                                 
Total params: 7,905
Trainable params: 7,905
Non-trainable params: 0
_________________________________________________________________


### VAE Class

In [14]:
class VAE(keras.Model):
    def __init__(self, encoder, decoder, **kwargs):
        super().__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.total_loss_tracker = keras.metrics.Mean(name="total_loss")
        self.reconstruction_loss_tracker = keras.metrics.Mean(
            name="reconstruction_loss"
        )
        self.kl_loss_tracker = keras.metrics.Mean(name="kl_loss")

    @property
    def metrics(self):
        return [
            self.total_loss_tracker,
            self.reconstruction_loss_tracker,
            self.kl_loss_tracker,
        ]

    def train_step(self, data):
        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)
            reconstruction_loss = tf.reduce_mean(
                keras.losses.mean_squared_error(data, reconstruction)
            )
            kl_loss = -0.5 * (
                1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var)
            )
            kl_loss = tf.reduce_mean(kl_loss)
            total_loss = reconstruction_loss + reg_lambda * kl_loss
        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))
        self.total_loss_tracker.update_state(total_loss)
        self.reconstruction_loss_tracker.update_state(reconstruction_loss)
        self.kl_loss_tracker.update_state(kl_loss)
        return {
            "loss": self.total_loss_tracker.result(),
            "reconstruction_loss": self.reconstruction_loss_tracker.result(),
            "kl_loss": self.kl_loss_tracker.result(),
        }

### Train VAE

In [15]:
reg_lambda=0
vae = VAE(encoder, decoder)
vae.compile(optimizer=keras.optimizers.Adam())
vae.fit(trainset, epochs=100, batch_size=128, verbose=2)

Epoch 1/100
625/625 - 1s - loss: 0.9483 - reconstruction_loss: 0.9483 - kl_loss: 22.0119 - 1s/epoch - 2ms/step
Epoch 2/100
625/625 - 1s - loss: 0.7894 - reconstruction_loss: 0.7894 - kl_loss: 36.1663 - 734ms/epoch - 1ms/step
Epoch 3/100
625/625 - 1s - loss: 0.7695 - reconstruction_loss: 0.7695 - kl_loss: 42.5368 - 731ms/epoch - 1ms/step
Epoch 4/100
625/625 - 1s - loss: 0.7623 - reconstruction_loss: 0.7623 - kl_loss: 44.1089 - 737ms/epoch - 1ms/step
Epoch 5/100
625/625 - 1s - loss: 0.7238 - reconstruction_loss: 0.7238 - kl_loss: 43.8560 - 734ms/epoch - 1ms/step
Epoch 6/100
625/625 - 1s - loss: 0.7028 - reconstruction_loss: 0.7028 - kl_loss: 42.9579 - 726ms/epoch - 1ms/step
Epoch 7/100
625/625 - 1s - loss: 0.6610 - reconstruction_loss: 0.6610 - kl_loss: 42.8889 - 729ms/epoch - 1ms/step
Epoch 8/100
625/625 - 1s - loss: 0.6563 - reconstruction_loss: 0.6563 - kl_loss: 43.2545 - 736ms/epoch - 1ms/step
Epoch 9/100
625/625 - 1s - loss: 0.6193 - reconstruction_loss: 0.6193 - kl_loss: 42.7185 - 

Epoch 73/100
625/625 - 1s - loss: 0.4085 - reconstruction_loss: 0.4085 - kl_loss: 34.9449 - 728ms/epoch - 1ms/step
Epoch 74/100
625/625 - 1s - loss: 0.4067 - reconstruction_loss: 0.4067 - kl_loss: 34.5703 - 725ms/epoch - 1ms/step
Epoch 75/100
625/625 - 1s - loss: 0.3701 - reconstruction_loss: 0.3701 - kl_loss: 34.2422 - 724ms/epoch - 1ms/step
Epoch 76/100
625/625 - 1s - loss: 0.3695 - reconstruction_loss: 0.3695 - kl_loss: 34.3819 - 724ms/epoch - 1ms/step
Epoch 77/100
625/625 - 1s - loss: 0.3689 - reconstruction_loss: 0.3689 - kl_loss: 34.4509 - 725ms/epoch - 1ms/step
Epoch 78/100
625/625 - 1s - loss: 0.3691 - reconstruction_loss: 0.3691 - kl_loss: 34.0168 - 723ms/epoch - 1ms/step
Epoch 79/100
625/625 - 1s - loss: 0.3687 - reconstruction_loss: 0.3687 - kl_loss: 33.6544 - 719ms/epoch - 1ms/step
Epoch 80/100
625/625 - 1s - loss: 0.3683 - reconstruction_loss: 0.3683 - kl_loss: 33.7283 - 723ms/epoch - 1ms/step
Epoch 81/100
625/625 - 1s - loss: 0.3683 - reconstruction_loss: 0.3683 - kl_loss